# Generated by Django 4.1.10 on 2023-08-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('email', models.EmailField(max_length=120, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone')),
                ('call_time', models.CharField(blank=True, max_length=120, null=True, verbose_name='Call time')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('address', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Feedback form',
                'verbose_name_plural': 'Feedback form',
            },
        ),
    ]
